services:
    traffic-switcher:
        container_name: traffic-switcher
        image: ghcr.io/marshallku/traffic-switcher:22
        pull_policy: always
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "1143:1143"
            - "1144:1144"
        volumes:
            - ./config.yaml:/usr/local/bin/config.yaml
        env_file:
            - .env
        environment:
            - HOST=0.0.0.0
            - PORT=1143
            - PROXY_PORT=1144

