services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.5.0
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - GENERIC_TIMEZONE=Asia/Seoul
      - TZ=Asia/Seoul
    volumes:
      - /mnt/hdd/data/n8n:/home/node/.n8n
      #- ~/.claude/:/home/node/.claude:ro
      #- ~/.claude.json:/home/node/.claude.json:ro
      - ~/.ssh/n8n_key:/home/node/.ssh/id_ed25519:ro
      - ./ssh_config:/home/node/.ssh/config:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  n8n_data:
