services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.0.1
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - GENERIC_TIMEZONE=Asia/Seoul
      - TZ=Asia/Seoul
    volumes:
      - /mnt/hdd/data/n8n:/home/node/.n8n
      - /Users/Shared/allCAbundle.pem:/certs/allCAbundle.pem:ro

volumes:
  n8n_data:
