services:
    database:
        image: mongo:${MONGO_TAG}
        restart: always
        container_name: blog-database
        ports:
            - ${MONGO_PORT}:27017
        networks:
            internal_network:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - /mnt/hdd/data/blog-backend/db:/data/db
            - /mnt/hdd/data/blog-backend/config:/data/configdb
    api:
        restart: unless-stopped
        container_name: blog-api
        image: ghcr.io/marshallku/blog-backend:latest
        depends_on:
            - database
        ports:
            - 48312:${PORT}
        env_file:
            - .env
        environment:
            - HOST=0.0.0.0
            - MONGO_HOST=172.18.0.1
            - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
            - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
            - TEMPLATE_PATH=templates/**/*.html
        networks:
            internal_network:
            app_network:

networks:
    app_network:
        external: true
    internal_network:
